save_data: data/run/example
## Where the vocab(s) will be written
src_vocab: hindibert/tgt.vocab
tgt_vocab: gujaratibert/src.vocab
# Prevent overwriting existing files in the folder
# overwrite: False

# Corpus opts:
data:
    train:
        path_src: data/guj-to-hin/tgt-train.txt
        path_tgt: data/guj-to-hin/src-train.txt
        transforms: [onmt_tokenize]
        weight: 1
    valid:
        path_src: data/guj-to-hin/tgt-val.txt
        path_tgt: data/guj-to-hin/src-val.txt
        transforms: [onmt_tokenize]

src_subword_model: hindibert/tgt.model
tgt_subword_model: gujaratibert/src.model

# train_from: model_step_50000.pt

# Number of candidates for SentencePiece sampling
subword_nbest: 20
# Smoothing parameter for SentencePiece sampling
subword_alpha: 0.1

# Specific arguments for pyonmttok
src_subword_type: sentencepiece
tgt_subword_type: sentencepiece
src_onmttok_kwargs: "{'mode': 'conservative', 'spacer_annotate': True}"
tgt_onmttok_kwargs: "{'mode': 'conservative', 'spacer_annotate': True}"

src_seq_length: 80
tgt_seq_length: 80

# Train on a single GPU
world_size: 1
gpu_ranks: [0]
save_checkpoint_steps: 10000
keep_checkpoint: 10
seed: 3435
train_steps: 150000
valid_steps: 10000
warmup_steps: 8000
report_every: 100

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
enc_layers: 3
dec_layers: 3
transformer_ff: 2048
heads: 8

accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 1
gpu_ranks:
- 0

